In [1]:
import numpy as np

In [2]:
np.array([5,4,6,78,8,3,3,54,6,8,8,12])

array([ 5,  4,  6, 78,  8,  3,  3, 54,  6,  8,  8, 12])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
np.linspace(1,10, num = 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
np.linspace(1,10, num = 20, retstep=True)

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [12]:
np.random.random()

0.19175920252608314

In [20]:
np.random.random(size=(4,5))

array([[0.53303706, 0.96914661, 0.01522804, 0.16793506, 0.46086225],
       [0.16476697, 0.2121016 , 0.42777422, 0.69348181, 0.64852234],
       [0.76093221, 0.13491973, 0.72239486, 0.9535169 , 0.83897321],
       [0.90441139, 0.06131915, 0.20633815, 0.23863941, 0.25344765]])

In [21]:
# normal distribution
np.random.randn(4,5)

array([[ 1.26223465,  1.21404536,  0.20108165, -1.40734892,  0.3261341 ],
       [ 0.6530947 , -0.15130648, -1.72859636,  1.29025931, -1.14016754],
       [-0.39402432, -0.99857324, -2.03849286,  0.39909243,  1.31574351],
       [-0.92836302,  1.66675084, -1.12926927,  0.10961268, -0.72731036]])

In [24]:
np.random.seed(4)
np.random.randint(1,100)

47

In [16]:
np.random.randint(1,100,10)

array([89, 75, 82, 47, 22, 85, 63, 90, 65, 82])

In [17]:
np.random.randint(1,100,(4,6))

array([[19, 81,  3,  5, 58,  9],
       [10, 57, 83, 69, 69, 75],
       [ 1, 92, 46, 65, 74, 49],
       [26, 44, 16, 70, 76, 97]])

In [18]:
x = np.random.randint(1,100,(4,6))

In [19]:
x

array([[58, 56, 28, 56, 62,  9],
       [87, 46, 63, 99, 16, 78],
       [64, 83, 55, 74, 76, 63],
       [19, 37, 17, 41, 41, 96]])

In [25]:
x.shape

(4, 6)

In [26]:
x.reshape((6,4))

array([[58, 56, 28, 56],
       [62,  9, 87, 46],
       [63, 99, 16, 78],
       [64, 83, 55, 74],
       [76, 63, 19, 37],
       [17, 41, 41, 96]])

In [28]:
x.reshape((6,-1))

array([[58, 56, 28, 56],
       [62,  9, 87, 46],
       [63, 99, 16, 78],
       [64, 83, 55, 74],
       [76, 63, 19, 37],
       [17, 41, 41, 96]])

In [29]:
y = x.flatten()

In [30]:
y

array([58, 56, 28, 56, 62,  9, 87, 46, 63, 99, 16, 78, 64, 83, 55, 74, 76,
       63, 19, 37, 17, 41, 41, 96])

In [31]:
np.mean(y)

55.166666666666664

In [32]:
np.median(y)

57.0

In [33]:
np.var(y)

621.9722222222222

In [34]:
np.max(y)

99

In [35]:
np.min(y)

9

In [36]:
np.sort(y)

array([ 9, 16, 17, 19, 28, 37, 41, 41, 46, 55, 56, 56, 58, 62, 63, 63, 64,
       74, 76, 78, 83, 87, 96, 99])

In [37]:
y

array([58, 56, 28, 56, 62,  9, 87, 46, 63, 99, 16, 78, 64, 83, 55, 74, 76,
       63, 19, 37, 17, 41, 41, 96])

In [38]:
y[0]

58

In [39]:
y[2]

28

In [41]:
# slicing
y[0:6]

array([58, 56, 28, 56, 62,  9])

In [42]:
y[-1]

96

In [43]:
y[10:0:-1]

array([16, 99, 63, 46, 87,  9, 62, 56, 28, 56])

In [44]:
x

array([[58, 56, 28, 56, 62,  9],
       [87, 46, 63, 99, 16, 78],
       [64, 83, 55, 74, 76, 63],
       [19, 37, 17, 41, 41, 96]])

In [45]:
x.T

array([[58, 87, 64, 19],
       [56, 46, 83, 37],
       [28, 63, 55, 17],
       [56, 99, 74, 41],
       [62, 16, 76, 41],
       [ 9, 78, 63, 96]])

In [46]:
x[0]

array([58, 56, 28, 56, 62,  9])

In [47]:
x[0:2]

array([[58, 56, 28, 56, 62,  9],
       [87, 46, 63, 99, 16, 78]])

In [48]:
x[:]

array([[58, 56, 28, 56, 62,  9],
       [87, 46, 63, 99, 16, 78],
       [64, 83, 55, 74, 76, 63],
       [19, 37, 17, 41, 41, 96]])

In [50]:
x[:, 0:1]

array([[58],
       [87],
       [64],
       [19]])

In [51]:
# rows - 0,1 and 2
# cols - 2,3 and 4
x[0:3, 2:5]

array([[28, 56, 62],
       [63, 99, 16],
       [55, 74, 76]])